version: '2.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./plugins/config/:/etc/logstash/pipeline/conf/
      - ./plugins/lib/mysql-connector-java-6.0.6.jar:/mysql-connector-java-6.0.6.jar
      - ./sync/:/usr/share/logstash/sync/:rw
      -  ~/etc/timezone:/etc/localtime:ro
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    user: root
    network_mode: host
    privileged: true
