version: '2.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
      - "network.host=0.0.0.0"
      - "http.cors.enabled=true"
    volumes:
      - elasticsearch-plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - elasticsearch-data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    ports:
      - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./plugins/config/:/etc/logstash/pipeline/conf/
      - ./plugins/lib/mysql-connector-java-6.0.6.jar:/mysql-connector-java-6.0.6.jar
      - ./sync/:/usr/share/logstash/sync/:rw
      - ~/etc/timezone:/etc/localtime:ro
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    user: root
    network_mode: host
    privileged: true
volumes:
  elasticsearch-plugins:
  elasticsearch-data: